apiVersion: apps/v1
kind: Deployment
metadata:
  name: dig
  labels:
    app: dig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dig
  template:
    metadata:
      labels:
        app: dig
    spec:
      containers:
      - name: dig
        image: sequenceiq/alpine-dig:latest
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80